name: "Setup MyCLI Workflow"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup-my-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install and run MyCLI
        run: |
          npm install -g my-cli
          my-cli --version
